---
kind: pipeline
type: kubernetes
name: linuxkit-armbian/pkgs

clone:
  skip_verify: true

steps:
  - name: git submodules
    image: alpine/git
    commands:
    - git submodule init
    - git submodule update --recursive --remote
  - name: build-pkgs
    image: alpine
    commands:
    - apk add bash jq patch
    - apk add yq docker-cli --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
    - |-
      dir=~/.docker/cli-plugins
      mkdir -p $dir &&
      wget -O $dir/docker-buildx https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64 &&
      chmod +x $dir/docker-buildx
    - echo 'ce6241324784b1c6581347cf213def47519205f9-arm' >linuxkit/tools/alpine/hash
    - DOCKER_HOST=http://dind:2376 scripts/build-pkgs.sh
---
kind: secret
name: dockerhub_username
get:
  path: docker-registry-dockerhub
  name: username
---
kind: secret
name: dockerhub_password
get:
  path: docker-registry-dockerhub
  name: password
