---
kind: pipeline
type: kubernetes
name: linuxkit-armbian/pkgs

clone:
  skip_verify: true

steps:
  - name: git submodules
    image: dockerregistry.lab.khoobyar.lan/builder
    commands:
    - git submodule init
    - git submodule update --recursive --remote
  - name: build-pkgs
    image: dockerregistry.lab.khoobyar.lan/builder
    pull: always
    commands:
    - mkdir -p linuxkit/tools/alpine
    - echo $ALPINE_BASE >linuxkit/tools/alpine/hash
    - /entrypoint.sh scripts/build-pkgs.sh
    environment:
      ALPINE_BASE: dockerregistry.lab.khoobyar.lan/linuxkit/alpine:ce6241324784b1c6581347cf213def47519205f9-armv7l
      BUILDX_INSTANCE:
        from_secret: buildx_instance
      DOCKER_CONFIGJSON:
        from_secret: docker_configjson
---
kind: secret
name: docker_configjson
get:
  path: builder-env
  name: config.json
---
kind: secret
name: buildx_instance
get:
  path: builder-env
  name: buildx-instance

