---
kind: pipeline
type: kubernetes
name: linuxkit-armbian/pkgs

clone:
  skip_verify: true

steps:
  - name: chown
    image: alpine
    commands:
    - chown -R 1000:1000 /drone/src
  - name: git submodules
    image: dockerregistry.lab.khoobyar.lan/builder
    commands:
    - git submodule init
    - git submodule update --recursive --remote
  - name: build-base
    image: dockerregistry.lab.khoobyar.lan/builder
    pull: always
    commands:
    - ls -l linuxkit/tools
    - /entrypoint.sh scripts/build.sh base
    environment:
      BUILDX_INSTANCE:
        from_secret: buildx_instance
      DOCKER_CONFIGJSON:
        from_secret: docker_configjson
  - name: build-pkgs
    image: dockerregistry.lab.khoobyar.lan/builder
    pull: always
    commands:
    - /entrypoint.sh scripts/build.sh all-pkg
    environment:
      BUILDX_INSTANCE:
        from_secret: buildx_instance
      DOCKER_CONFIGJSON:
        from_secret: docker_configjson
---
kind: secret
name: docker_configjson
get:
  path: builder-env
  name: config.json
---
kind: secret
name: buildx_instance
get:
  path: builder-env
  name: buildx-instance

