kernel:
  image: harbor.lab.khoobyar.lan/linuxkit/kernel:vexpress-a15-5.4.0-92.103
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - harbor.lab.khoobyar.lan/linuxkit/init:latest-armv7l
  - harbor.lab.khoobyar.lan/linuxkit/runc:latest-armv7l
  - harbor.lab.khoobyar.lan/linuxkit/containerd:latest-armv7l
  - harbor.lab.khoobyar.lan/linuxkit/ca-certificates:latest-armv7l
onboot:
  - name: sysctl
    image: harbor.lab.khoobyar.lan/linuxkit/sysctl:latest-armv7l
  - name: rngd1
    image: harbor.lab.khoobyar.lan/linuxkit/rngd:latest-armv7l
    command: ["/sbin/rngd", "-1"]
  - name: dhcpcd
    image: harbor.lab.khoobyar.lan/linuxkit/dhcpcd:latest-armv7l
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
onshutdown:
  - name: shutdown
    image: busybox:latest
    command: ["/bin/echo", "so long and thanks for all the fish"]
services:
  - name: getty
    image: harbor.lab.khoobyar.lan/linuxkit/getty:latest-armv7l
    env:
     - INSECURE=true
  - name: rngd
    image: harbor.lab.khoobyar.lan/linuxkit/rngd:latest-armv7l
  - name: sshd
    image: harbor.lab.khoobyar.lan/linuxkit/sshd:latest-armv7l
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_ecdsa.pub
    mode: "0600"
    optional: true
